### ISSUE TITLE
Requirements Checklist

### ISSUE THREAD

**Issue by poplexity** [telosnetwork/ptokens-swap#3]
# Contract

- [ ] Contract receives pToken TLOS and sends back OFT TLOS at a ratio of 1:1
- [ ] Owner of contract can withdraw either token in the case of users sending directly to contract by accident
- [ ] Contract can only redeem as much pToken TLOS as it has OFT TLOS in it's own balance

# UI

- [ ] Should have very simple feel, light Telos branding (no header/menu)
- [ ] Login with all supported wallets
- [ ] Disconnect button when logged in
- [ ] Show balance of pToken with a button to swap it
- [ ] Show in smaller text the balance of OFT
- [ ] When clicked, the swap button does an approval
- [ ] Once approved, user is prompted to call the swap function
- [ ] Balances are updated
