### ISSUE TITLE
[EPIC] List of changes

### ISSUE THREAD

**Issue by poplexity** [telosnetwork/ptokens-swap#5]
- [x] Favicon should be Telos branded
- [x] Title should be "pToken TLOS <> OFT TLOS migration" (TBD, might change this again based on internal feedback)
- [ ] Phantom wallet icon not loading, it seems to be dynamically adding itself
- [ ] Injected needs a more descriptive label... maybe "Brave/Coinbase/etc.."
- [x] When a user has more pToken TLOS than the contract has, we should warn them and let them swap the contract balance
- [x] Make connected wallet address a link to explorer
- [x] Change the concept _swap_ for _migration_
----
**update from @pmjanus suggestions"
- [ ] Add the logo of the network at the side of the network name
- [ ] Display the connected address in the top-right corner, tiny and handy,
- [ ] Localize the text for supported languages.
- [ ] Round balance values to two decimal places.
- [ ] Add a link to Telegram for support or additional information.
- [ ] Highlight the redemption limit based on the migration contract.
- [ ] Include a message explaining the periodic refilling of the migration contract using the text: "The migration contract is filled periodically, and the redemption amount is restricted based on the account's limitations."
- [ ] Verify the links to the OFT and pTLOS contracts.

![image](https://github.com/user-attachments/assets/beca7453-6e9e-4d39-ae71-8e05f1467ebc)

----

**update from the chat**
- [x] make the design more responsive
![image](https://github.com/user-attachments/assets/0f9c4f61-75f3-45ea-85be-ec55895b188d)

**Comment by Viterbo** [comment]
reopening
